# Generated by Django 3.1.4 on 2021-01-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_auto_20210128_1005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catergory',
        ),
    ]
